---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/posts/{id}/comments":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: list apicomments
      responses:
        '200':
          description: successful
  "/api/posts/{id}/comments/create":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    post:
      summary: create apicomment
      responses:
        '200':
          description: successful
  "/api/users/{id}/posts":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: list apiposts
      parameters:
      - name: id
        in: path
        description: id of the user
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    text:
                      type: string
                    comments_counter:
                      type: integer
                    likes_counter:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                    author_id:
                      type: integer
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
